config/routes.rb
Celebtwitters::Application.routes.draw do
  resources :celebtwits

end

app/models/celebtwit.rb
class Celebtwit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/celebtwits_controller.rb
class CelebtwitsController < ApplicationController
  before_action :set_celebtwit, only: [:show, :edit, :update, :destroy]

  # GET /celebtwits
  # GET /celebtwits.json
  def index
    @celebtwits = Celebtwit.all
  end

  # GET /celebtwits/1
  # GET /celebtwits/1.json
  def show
  end

  # GET /celebtwits/new
  def new
    @celebtwit = Celebtwit.new
  end

  # GET /celebtwits/1/edit
  def edit
  end

  # POST /celebtwits
  # POST /celebtwits.json
  def create
    @celebtwit = Celebtwit.new(celebtwit_params)

    respond_to do |format|
      if @celebtwit.save
        format.html { redirect_to @celebtwit, notice: 'Celebtwit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @celebtwit }
      else
        format.html { render action: 'new' }
        format.json { render json: @celebtwit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /celebtwits/1
  # PATCH/PUT /celebtwits/1.json
  def update
    respond_to do |format|
      if @celebtwit.update(celebtwit_params)
        format.html { redirect_to @celebtwit, notice: 'Celebtwit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @celebtwit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celebtwits/1
  # DELETE /celebtwits/1.json
  def destroy
    @celebtwit.destroy
    respond_to do |format|
      format.html { redirect_to celebtwits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_celebtwit
      @celebtwit = Celebtwit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def celebtwit_params
      params.require(:celebtwit).permit(:name, :acct)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celebtwits_helper.rb
module CelebtwitsHelper
end

app/views/celebtwits/_form.html.erb
<%= form_for(@celebtwit) do |f| %>
  <% if @celebtwit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@celebtwit.errors.count, "error") %> prohibited this celebtwit from being saved:</h2>

      <ul>
      <% @celebtwit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :acct %><br>
    <%= f.text_field :acct %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/celebtwits/edit.html.erb
<h1>Editing celebtwit</h1>

<%= render 'form' %>

<%= link_to 'Show', @celebtwit %> |
<%= link_to 'Back', celebtwits_path %>

app/views/celebtwits/index.html.erb
<h1>Listing celebtwits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Acct</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @celebtwits.each do |celebtwit| %>
      <tr>
        <td><%= celebtwit.name %></td>
        <td><%= celebtwit.acct %></td>
        <td><%= link_to 'Show', celebtwit %></td>
        <td><%= link_to 'Edit', edit_celebtwit_path(celebtwit) %></td>
        <td><%= link_to 'Destroy', celebtwit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Celebtwit', new_celebtwit_path %>

app/views/celebtwits/new.html.erb
<h1>New celebtwit</h1>

<%= render 'form' %>

<%= link_to 'Back', celebtwits_path %>

app/views/celebtwits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @celebtwit.name %>
</p>

<p>
  <strong>Acct:</strong>
  <%= @celebtwit.acct %>
</p>

<%= link_to 'Edit', edit_celebtwit_path(@celebtwit) %> |
<%= link_to 'Back', celebtwits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Celebtwitters</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>